name: First_Workflow
on: push
jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: Welcome Message
              run: echo "This is my first Github Action Job!"
            
            - name: List Files
              run: ls -la

            - name: Print Processes
              run: ps -au